apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: voting-app
spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app
    spec:
      containers:
      - name: postgres
        image: postgres
        ports: 
        - containerPort: 5432                           # Port on which the app is listening
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
  replicas: 1
  selector: 
    matchLabels:
      name: postgres-pod
      app: voting-app
