apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: voting-app
spec:
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports: 
        - containerPort: 80                           # Port on which the app is listening
  replicas: 1
  selector: 
    matchLabels:
      name: voting-app-pod
      app: voting-app
